#!/usr/bin/env bash

CUDA_VISIBLE_DEVICES=0 python search_pre_hidden.py \
-gen_bs 128 \
-dis_bs 64 \
--dataset cifar10 \
--bottom_width 4 \
--img_size 32 \
--gen_model shared_gan_pre_orign \
--dis_model shared_gan_pre_orign \
--teacher_gen_b teacher_gen_a_pre \
--controller_block controller_ITS_orign \
--latent_dim 128 \
--gf_dim 128 \
--df_dim 64 \
--tea_gf_dim 128 \
--tea_df_dim 128 \
--g_spectral_norm False \
--d_spectral_norm True \
--g_lr 0.0002 \
--d_lr 0.0002 \
--beta1 0.0 \
--beta2 0.9 \
--init_type xavier_uniform \
--n_critic 5 \
--val_freq 20 \
--ctrl_sample_batch 1 \
--num_candidate 10 \
--topk 5 \
--shared_epoch 15 \
--grow_step1 15 \
--grow_step2 35 \
--grow_step3 60 \
--max_search_iter 90 \
--ctrl_step 30 \
--exp_name autogan_search